# Generated by Django 4.0.3 on 2022-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('pattern', models.CharField(max_length=10)),
            ],
        ),
    ]
